services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "37017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping: 1}) && db.getCollectionNames().length >= 0"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - ./docker-env
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${AUTH_PORT}/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product-service
    env_file:
      - ./docker-env
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PRODUCT_PORT}/api/products/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order-service
    env_file:
      - ./docker-env
    ports:
      - "${ORDER_PORT}:${ORDER_PORT}"
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${ORDER_PORT}/api/orders/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    env_file:
      - ./docker-env
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    restart: always
    depends_on:
      auth-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${API_GATEWAY_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: