name: CI/CD Pipeline (NodeJS Microservices)

on:
  push:
    branches: [ "main" ]

jobs:
  ci_cd_pipeline:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout source code
      - uses: actions/checkout@v4

      # Step 2: Allow PowerShell scripts
      - name: Allow PowerShell scripts
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        shell: powershell

      # Step 3: Clean old Docker environment
      - name: Clean old Docker environment
        shell: powershell
        run: |
          Write-Host "Stopping all containers..."
          docker ps -aq | ForEach-Object { docker stop $_; docker rm -f $_ }
          docker network prune -f
          docker volume prune -f
          docker system prune -af
          Write-Host "Docker environment cleaned up!"

      # Step 4: Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Generate env file for Docker Compose
      - name: Generate env file for Docker Compose
        shell: powershell
        run: |
          $envFile = @"
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}
          MONGODB_PRODUCT_URI=${{ vars.MONGODB_PRODUCT_URI }}
          MONGODB_ORDER_URI=${{ vars.MONGODB_ORDER_URI }}
          MONGODB_AUTH_URI=${{ vars.MONGODB_AUTH_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          AUTH_SERVICE_URI=${{ vars.AUTH_SERVICE_URI }}
          RABBITMQ_URI=${{ vars.RABBITMQ_URI }}
          RABBITMQ_QUEUE=${{ vars.RABBITMQ_QUEUE }}
          PRODUCT_PORT=${{ vars.PRODUCT_PORT }}
          ORDER_PORT=${{ vars.ORDER_PORT }}
          AUTH_PORT=${{ vars.AUTH_PORT }}
          API_GATEWAY_PORT=${{ vars.API_GATEWAY_PORT }}
          "@
          $envFile | Out-File -Encoding ascii -FilePath docker-env
          Write-Host "Env file generated!"

      # Step 6: Build & run services
      - name: Build and start services
        shell: powershell
        run: |
          docker compose --env-file docker-env -p eproject down -v --remove-orphans
          docker compose --env-file docker-env -p eproject up -d --build
          Write-Host "Services built and started!"

      # Step 7: Wait for MongoDB & RabbitMQ
      - name: Wait for MongoDB & RabbitMQ
        shell: powershell
        run: |
          Write-Host "Waiting for MongoDB & RabbitMQ..."
          Start-Sleep -Seconds 15
          docker ps

      # Step 8: Test API (Health Check)
      - name: Test API Health
        shell: powershell
        run: |
          Write-Host "Checking API health..."
          try {
            $response = Invoke-RestMethod -Uri "http://localhost:${{ vars.API_GATEWAY_PORT }}/health" -TimeoutSec 10
            Write-Host "API Health: $($response)"
          } catch {
            Write-Host "API health check failed!"
            exit 1
          }

      # Step 9: Push image lên DockerHub
      - name: Push images to DockerHub
        shell: powershell
        run: docker compose -p eproject push